import {
  ArrowCircleDown,
  ArrowCircleUp,
  ArrowClockwise,
  ArrowLeft,
  ArrowSquareOut,
  BookBookmark,
  Bookmark,
  CaretDown,
  CaretUp,
  CloudRain,
  Crosshair,
  DotsThreeOutlineVertical,
  Drop,
  Funnel,
  GearSix,
  HeadCircuit,
  Info,
  List,
  MagnifyingGlass,
  MapPin,
  MapPinArea,
  Plus,
  RssSimple,
  ShareNetwork,
  Sparkle,
  Sun,
  Trash,
  Wind,
  X,
} from 'phosphor-react-native'

import {
  Sun as SunSVG,
  Moon as MoonSVG,
  Cloud,
  CloudDay,
  CloudNight,
  ThunderstormDay,
  MistDay,
  ThunderstormNight,
  MistNight,
  SnowNight,
  RainNight,
  RainDay,
  SnowDay,
} from '@/assets/weatherIcons'

export const IconMap = {
  gearSix: GearSix,
  list: List,
  dotsThreeOutlineVertical: DotsThreeOutlineVertical,
  mapPin: MapPin,
  crosshair: Crosshair,
  magnifyingGlass: MagnifyingGlass,
  mapPinArea: MapPinArea,
  cloudRain: CloudRain,
  drop: Drop,
  sun: Sun,
  wind: Wind,
  plus: Plus,
  trash: Trash,
  caretDown: CaretDown,
  caretUp: CaretUp,
  headCircuit: HeadCircuit,
  sparkle: Sparkle,
  shareNetwork: ShareNetwork,
  bookMark: Bookmark,
  bookBookmark: BookBookmark,
  arrowClockwise: ArrowClockwise,
  arrowSquareOut: ArrowSquareOut,
  arrowCircleUp: ArrowCircleUp,
  arrowCircleDown: ArrowCircleDown,
  arrowLeft: ArrowLeft,
  info: Info,
  funnel: Funnel,
  rssSimple: RssSimple,
  x: X,
} as const

export type IconMapKeyType = keyof typeof IconMap

export const iconSVGMap = {
  sun: SunSVG,
  thunderstormDay: ThunderstormDay,
  mistDay: MistDay,
  rainDay: RainDay,
  snowDay: SnowDay,
  cloudDay: CloudDay,
  cloud: Cloud,
  moon: MoonSVG,
  thunderstormNight: ThunderstormNight,
  mistNight: MistNight,
  rainNight: RainNight,
  snowNight: SnowNight,
  cloudNight: CloudNight,
} as const

export type IconSVGMapKeyType = keyof typeof iconSVGMap
