import {
  ArrowCircleDown,
  ArrowCircleUp,
  ArrowSquareOut,
  Bookmark,
  CaretDown,
  CaretUp,
  CloudRain,
  Crosshair,
  DotsThreeOutlineVertical,
  Drop,
  GearSix,
  HeadCircuit,
  Info,
  List,
  MagnifyingGlass,
  MapPin,
  MapPinArea,
  Plus,
  Sparkle,
  Sun,
  Wind,
  X,
} from 'phosphor-react-native'

import {
  Sun as SunSVG,
  Moon as MoonSVG,
  Cloud,
  CloudDay,
  CloudNight,
  ThunderstormDay,
  MistDay,
  ThunderstormNight,
  MistNight,
  SnowNight,
  RainNight,
  RainDay,
  SnowDay,
} from '@/assets/weatherIcons'

export const IconMap = {
  gearSix: GearSix,
  list: List,
  dotsThreeOutlineVertical: DotsThreeOutlineVertical,
  mapPin: MapPin,
  crosshair: Crosshair,
  magnifyingGlass: MagnifyingGlass,
  mapPinArea: MapPinArea,
  cloudRain: CloudRain,
  drop: Drop,
  sun: Sun,
  wind: Wind,
  plus: Plus,
  caretDown: CaretDown,
  caretUp: CaretUp,
  headCircuit: HeadCircuit,
  sparkle: Sparkle,
  bookMark: Bookmark,
  arrowSquareOut: ArrowSquareOut,
  arrowCircleUp: ArrowCircleUp,
  arrowCircleDown: ArrowCircleDown,
  info: Info,
  x: X,
} as const

export type IconMapKeyType = keyof typeof IconMap

export const iconSVGMap = {
  sun: SunSVG,
  thunderstormDay: ThunderstormDay,
  mistDay: MistDay,
  rainDay: RainDay,
  snowDay: SnowDay,
  cloudDay: CloudDay,
  cloud: Cloud,
  moon: MoonSVG,
  thunderstormNight: ThunderstormNight,
  mistNight: MistNight,
  rainNight: RainNight,
  snowNight: SnowNight,
  cloudNight: CloudNight,
} as const

export type IconSVGMapKeyType = keyof typeof iconSVGMap
